name = "privacyterminal"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "privacyterminal-db"
database_id = "cae063fe-4e09-427e-bf54-3767f48278fe"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "privacyterminal_analytics"
